
resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 3
        slow-call-rate-threshold: 10
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 120s
        wait-duration-in-open-state: 120s
        slow-call-duration-threshold: 10s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 10
    instances:
      netsurfing-topic-cb:
        base-config: shared

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages=com.netsurfingzone.*
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable:
        auto:
          commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
